baseURL = "https://marcellacafe.netlify.app/"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"
title = "Marcella Café"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "Sobre"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3
  
  [[menu.header]]
  name = "Cursos"
  URL = "#testimonial"
  weight = 4

  [[menu.header]]
  name = "Contato"
  URL = "#contact"
  weight = 5


  [[menu.footer]]
  name = "Sobre"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3
  
  [[menu.footer]]
  name = "Cursos"
  URL = "#testimonial"
  weight = 4

  [[menu.footer]]
  name = "Contato"
  URL = "#contact"
  weight = 5


[params]

  sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Marcella"
    text2 = "Café"

  [params.footer]
      copyright = "© Marcella Café. All rights reserved."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"
